### ISSUE TITLE
Lucid is not working with tensorflow 2.0

### ISSUE THREAD

**Issue by sundara26071978** [tensorflow/lucid#250]
ImportError: cannot import name 'gfile' from 'tensorflow' (/Users/sunjsg/opt/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py)

**Comment by colah** [comment]
As per the first few lines of our readme, we do not support TF 2.0 at this time:

![image](https://user-images.githubusercontent.com/61658/82156699-aeb2e300-9831-11ea-95a3-31e68b63abee.png)
